# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: gazi92.github.io
google_analytics: dbyll
title: 오만가지

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 오.만.가.지 Gazi의 개발 블로그

description: Gazi Blog
author:
  name: Gazi92
  email: jjy8464@gmail.com
  github: Gazi92
  linkedin: Gazi92
  bio: 개발에 관한 오만가지 생각과 지식들을 채워넣을 예정입니다.
#rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
